/*
 * Visier Permission Management APIs
 * Visier APIs for managing permissions within an organization
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.RelatedAnalyticObjectDTO;
import com.konfigthis.client.model.SecurableDimensionDTO;
import com.konfigthis.client.model.SecurablePropertyDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AnalyticObjectDTO
 */
public class AnalyticObjectDTOTest {
    private final AnalyticObjectDTO model = new AnalyticObjectDTO();

    /**
     * Model tests for AnalyticObjectDTO
     */
    @Test
    public void testAnalyticObjectDTO() {
        // TODO: test AnalyticObjectDTO
    }

    /**
     * Test the property 'analyticObjectId'
     */
    @Test
    public void analyticObjectIdTest() {
        // TODO: test analyticObjectId
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'objectType'
     */
    @Test
    public void objectTypeTest() {
        // TODO: test objectType
    }

    /**
     * Test the property 'relatedObjects'
     */
    @Test
    public void relatedObjectsTest() {
        // TODO: test relatedObjects
    }

    /**
     * Test the property 'securableProperties'
     */
    @Test
    public void securablePropertiesTest() {
        // TODO: test securableProperties
    }

    /**
     * Test the property 'securableDimensions'
     */
    @Test
    public void securableDimensionsTest() {
        // TODO: test securableDimensions
    }

}
