/*
 * Visier Permission Management APIs
 * Visier APIs for managing permissions within an organization
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.InheritedAccessConfigDTO;
import com.konfigthis.client.model.MemberFilterConfigDTO;
import com.konfigthis.client.model.PropertySetConfigDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DataSecurityProfileDTO
 */
public class DataSecurityProfileDTOTest {
    private final DataSecurityProfileDTO model = new DataSecurityProfileDTO();

    /**
     * Model tests for DataSecurityProfileDTO
     */
    @Test
    public void testDataSecurityProfileDTO() {
        // TODO: test DataSecurityProfileDTO
    }

    /**
     * Test the property 'analyticObjectId'
     */
    @Test
    public void analyticObjectIdTest() {
        // TODO: test analyticObjectId
    }

    /**
     * Test the property 'propertySetConfig'
     */
    @Test
    public void propertySetConfigTest() {
        // TODO: test propertySetConfig
    }

    /**
     * Test the property 'allDataPointAccess'
     */
    @Test
    public void allDataPointAccessTest() {
        // TODO: test allDataPointAccess
    }

    /**
     * Test the property 'memberFilterConfigs'
     */
    @Test
    public void memberFilterConfigsTest() {
        // TODO: test memberFilterConfigs
    }

    /**
     * Test the property 'inheritedAccessConfigs'
     */
    @Test
    public void inheritedAccessConfigsTest() {
        // TODO: test inheritedAccessConfigs
    }

}
