/*
 * Visier Permission Management APIs
 * Visier APIs for managing permissions within an organization
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.DynamicPropertyMappingDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DynamicDimensionFilterDTO
 */
public class DynamicDimensionFilterDTOTest {
    private final DynamicDimensionFilterDTO model = new DynamicDimensionFilterDTO();

    /**
     * Model tests for DynamicDimensionFilterDTO
     */
    @Test
    public void testDynamicDimensionFilterDTO() {
        // TODO: test DynamicDimensionFilterDTO
    }

    /**
     * Test the property 'dimensionId'
     */
    @Test
    public void dimensionIdTest() {
        // TODO: test dimensionId
    }

    /**
     * Test the property 'subjectReferencePath'
     */
    @Test
    public void subjectReferencePathTest() {
        // TODO: test subjectReferencePath
    }

    /**
     * Test the property 'dynamicPropertyMappings'
     */
    @Test
    public void dynamicPropertyMappingsTest() {
        // TODO: test dynamicPropertyMappings
    }

}
