/*
 * Visier Permission Management APIs
 * Visier APIs for managing permissions within an organization
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.UserPropertyDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DynamicPropertyMappingDTO
 */
public class DynamicPropertyMappingDTOTest {
    private final DynamicPropertyMappingDTO model = new DynamicPropertyMappingDTO();

    /**
     * Model tests for DynamicPropertyMappingDTO
     */
    @Test
    public void testDynamicPropertyMappingDTO() {
        // TODO: test DynamicPropertyMappingDTO
    }

    /**
     * Test the property 'hierarchyPropertyId'
     */
    @Test
    public void hierarchyPropertyIdTest() {
        // TODO: test hierarchyPropertyId
    }

    /**
     * Test the property 'userProperty'
     */
    @Test
    public void userPropertyTest() {
        // TODO: test userProperty
    }

}
