/*
 * Visier Permission Management APIs
 * Visier APIs for managing permissions within an organization
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AdminCapabilityConfigDTO;
import com.konfigthis.client.model.DataSecurityProfileDTO;
import com.konfigthis.client.model.RoleModulesConfigDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PermissionDTO
 */
public class PermissionDTOTest {
    private final PermissionDTO model = new PermissionDTO();

    /**
     * Model tests for PermissionDTO
     */
    @Test
    public void testPermissionDTO() {
        // TODO: test PermissionDTO
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'permissionId'
     */
    @Test
    public void permissionIdTest() {
        // TODO: test permissionId
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'dataSecurityProfiles'
     */
    @Test
    public void dataSecurityProfilesTest() {
        // TODO: test dataSecurityProfiles
    }

    /**
     * Test the property 'adminCapabilityConfig'
     */
    @Test
    public void adminCapabilityConfigTest() {
        // TODO: test adminCapabilityConfig
    }

    /**
     * Test the property 'roleModulesConfig'
     */
    @Test
    public void roleModulesConfigTest() {
        // TODO: test roleModulesConfig
    }

}
