/*
 * Visier Permission Management APIs
 * Visier APIs for managing permissions within an organization
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PropertyAccessConfigDTO
 */
public class PropertyAccessConfigDTOTest {
    private final PropertyAccessConfigDTO model = new PropertyAccessConfigDTO();

    /**
     * Model tests for PropertyAccessConfigDTO
     */
    @Test
    public void testPropertyAccessConfigDTO() {
        // TODO: test PropertyAccessConfigDTO
    }

    /**
     * Test the property 'propertyId'
     */
    @Test
    public void propertyIdTest() {
        // TODO: test propertyId
    }

    /**
     * Test the property 'analyticObjectId'
     */
    @Test
    public void analyticObjectIdTest() {
        // TODO: test analyticObjectId
    }

    /**
     * Test the property 'analyticObjectReferencePaths'
     */
    @Test
    public void analyticObjectReferencePathsTest() {
        // TODO: test analyticObjectReferencePaths
    }

    /**
     * Test the property 'accessLevel'
     */
    @Test
    public void accessLevelTest() {
        // TODO: test accessLevel
    }

}
