/*
 * Visier Permission Management APIs
 * Visier APIs for managing permissions within an organization
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PropertyAccessConfigDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PropertySetConfigDTO
 */
public class PropertySetConfigDTOTest {
    private final PropertySetConfigDTO model = new PropertySetConfigDTO();

    /**
     * Model tests for PropertySetConfigDTO
     */
    @Test
    public void testPropertySetConfigDTO() {
        // TODO: test PropertySetConfigDTO
    }

    /**
     * Test the property 'propertyAccessConfigs'
     */
    @Test
    public void propertyAccessConfigsTest() {
        // TODO: test propertyAccessConfigs
    }

}
