/*
 * Visier Permission Management APIs
 * Visier APIs for managing permissions within an organization
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RelatedAnalyticObjectDTO
 */
public class RelatedAnalyticObjectDTOTest {
    private final RelatedAnalyticObjectDTO model = new RelatedAnalyticObjectDTO();

    /**
     * Model tests for RelatedAnalyticObjectDTO
     */
    @Test
    public void testRelatedAnalyticObjectDTO() {
        // TODO: test RelatedAnalyticObjectDTO
    }

    /**
     * Test the property 'analyticObjectId'
     */
    @Test
    public void analyticObjectIdTest() {
        // TODO: test analyticObjectId
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

}
