/*
 * Visier Permission Management APIs
 * Visier APIs for managing permissions within an organization
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.HierarchyPropertyDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SecurableDimensionDTO
 */
public class SecurableDimensionDTOTest {
    private final SecurableDimensionDTO model = new SecurableDimensionDTO();

    /**
     * Model tests for SecurableDimensionDTO
     */
    @Test
    public void testSecurableDimensionDTO() {
        // TODO: test SecurableDimensionDTO
    }

    /**
     * Test the property 'dimensionId'
     */
    @Test
    public void dimensionIdTest() {
        // TODO: test dimensionId
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'analyticObjectIds'
     */
    @Test
    public void analyticObjectIdsTest() {
        // TODO: test analyticObjectIds
    }

    /**
     * Test the property 'hierarchyProperties'
     */
    @Test
    public void hierarchyPropertiesTest() {
        // TODO: test hierarchyProperties
    }

}
