/*
 * Visier Permission Management APIs
 * Visier APIs for managing permissions within an organization
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SecurablePropertyDTO
 */
public class SecurablePropertyDTOTest {
    private final SecurablePropertyDTO model = new SecurablePropertyDTO();

    /**
     * Model tests for SecurablePropertyDTO
     */
    @Test
    public void testSecurablePropertyDTO() {
        // TODO: test SecurablePropertyDTO
    }

    /**
     * Test the property 'propertyId'
     */
    @Test
    public void propertyIdTest() {
        // TODO: test propertyId
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'analyticObjectId'
     */
    @Test
    public void analyticObjectIdTest() {
        // TODO: test analyticObjectId
    }

    /**
     * Test the property 'isPrimaryKey'
     */
    @Test
    public void isPrimaryKeyTest() {
        // TODO: test isPrimaryKey
    }

    /**
     * Test the property 'referenceSymbolName'
     */
    @Test
    public void referenceSymbolNameTest() {
        // TODO: test referenceSymbolName
    }

}
