/*
 * Visier Permission Management APIs
 * Visier APIs for managing permissions within an organization
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PermissionFailureDTO;
import com.konfigthis.client.model.PermissionSuccessDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * PermissionBulkOperationResponseDTO
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PermissionBulkOperationResponseDTO {
  public static final String SERIALIZED_NAME_SUCCESSES = "successes";
  @SerializedName(SERIALIZED_NAME_SUCCESSES)
  private List<PermissionSuccessDTO> successes = null;

  public static final String SERIALIZED_NAME_FAILURES = "failures";
  @SerializedName(SERIALIZED_NAME_FAILURES)
  private List<PermissionFailureDTO> failures = null;

  public PermissionBulkOperationResponseDTO() {
  }

  public PermissionBulkOperationResponseDTO successes(List<PermissionSuccessDTO> successes) {
    
    
    
    
    this.successes = successes;
    return this;
  }

  public PermissionBulkOperationResponseDTO addSuccessesItem(PermissionSuccessDTO successesItem) {
    if (this.successes == null) {
      this.successes = new ArrayList<>();
    }
    this.successes.add(successesItem);
    return this;
  }

   /**
   * The successfully processed permissions.
   * @return successes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The successfully processed permissions.")

  public List<PermissionSuccessDTO> getSuccesses() {
    return successes;
  }


  public void setSuccesses(List<PermissionSuccessDTO> successes) {
    
    
    
    this.successes = successes;
  }


  public PermissionBulkOperationResponseDTO failures(List<PermissionFailureDTO> failures) {
    
    
    
    
    this.failures = failures;
    return this;
  }

  public PermissionBulkOperationResponseDTO addFailuresItem(PermissionFailureDTO failuresItem) {
    if (this.failures == null) {
      this.failures = new ArrayList<>();
    }
    this.failures.add(failuresItem);
    return this;
  }

   /**
   * The permissions that did not process and any relevant error information.
   * @return failures
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The permissions that did not process and any relevant error information.")

  public List<PermissionFailureDTO> getFailures() {
    return failures;
  }


  public void setFailures(List<PermissionFailureDTO> failures) {
    
    
    
    this.failures = failures;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PermissionBulkOperationResponseDTO instance itself
   */
  public PermissionBulkOperationResponseDTO putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PermissionBulkOperationResponseDTO permissionBulkOperationResponseDTO = (PermissionBulkOperationResponseDTO) o;
    return Objects.equals(this.successes, permissionBulkOperationResponseDTO.successes) &&
        Objects.equals(this.failures, permissionBulkOperationResponseDTO.failures)&&
        Objects.equals(this.additionalProperties, permissionBulkOperationResponseDTO.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(successes, failures, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PermissionBulkOperationResponseDTO {\n");
    sb.append("    successes: ").append(toIndentedString(successes)).append("\n");
    sb.append("    failures: ").append(toIndentedString(failures)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("successes");
    openapiFields.add("failures");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PermissionBulkOperationResponseDTO
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PermissionBulkOperationResponseDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PermissionBulkOperationResponseDTO is not found in the empty JSON string", PermissionBulkOperationResponseDTO.openapiRequiredFields.toString()));
        }
      }
      if (jsonObj.get("successes") != null && !jsonObj.get("successes").isJsonNull()) {
        JsonArray jsonArraysuccesses = jsonObj.getAsJsonArray("successes");
        if (jsonArraysuccesses != null) {
          // ensure the json data is an array
          if (!jsonObj.get("successes").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `successes` to be an array in the JSON string but got `%s`", jsonObj.get("successes").toString()));
          }

          // validate the optional field `successes` (array)
          for (int i = 0; i < jsonArraysuccesses.size(); i++) {
            PermissionSuccessDTO.validateJsonObject(jsonArraysuccesses.get(i).getAsJsonObject());
          };
        }
      }
      if (jsonObj.get("failures") != null && !jsonObj.get("failures").isJsonNull()) {
        JsonArray jsonArrayfailures = jsonObj.getAsJsonArray("failures");
        if (jsonArrayfailures != null) {
          // ensure the json data is an array
          if (!jsonObj.get("failures").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `failures` to be an array in the JSON string but got `%s`", jsonObj.get("failures").toString()));
          }

          // validate the optional field `failures` (array)
          for (int i = 0; i < jsonArrayfailures.size(); i++) {
            PermissionFailureDTO.validateJsonObject(jsonArrayfailures.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PermissionBulkOperationResponseDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PermissionBulkOperationResponseDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PermissionBulkOperationResponseDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PermissionBulkOperationResponseDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<PermissionBulkOperationResponseDTO>() {
           @Override
           public void write(JsonWriter out, PermissionBulkOperationResponseDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PermissionBulkOperationResponseDTO read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PermissionBulkOperationResponseDTO instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PermissionBulkOperationResponseDTO given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PermissionBulkOperationResponseDTO
  * @throws IOException if the JSON string is invalid with respect to PermissionBulkOperationResponseDTO
  */
  public static PermissionBulkOperationResponseDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PermissionBulkOperationResponseDTO.class);
  }

 /**
  * Convert an instance of PermissionBulkOperationResponseDTO to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

