/*
 * Visier Permission Management APIs
 * Visier APIs for managing permissions within an organization
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AdminCapabilityConfigDTO;
import com.konfigthis.client.model.DataSecurityProfileDTO;
import com.konfigthis.client.model.RoleModulesConfigDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * PermissionDTO
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PermissionDTO {
  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_PERMISSION_ID = "permissionId";
  @SerializedName(SERIALIZED_NAME_PERMISSION_ID)
  private String permissionId;

  public static final String SERIALIZED_NAME_DISPLAY_NAME = "displayName";
  @SerializedName(SERIALIZED_NAME_DISPLAY_NAME)
  private String displayName;

  public static final String SERIALIZED_NAME_DATA_SECURITY_PROFILES = "dataSecurityProfiles";
  @SerializedName(SERIALIZED_NAME_DATA_SECURITY_PROFILES)
  private List<DataSecurityProfileDTO> dataSecurityProfiles = null;

  public static final String SERIALIZED_NAME_ADMIN_CAPABILITY_CONFIG = "adminCapabilityConfig";
  @SerializedName(SERIALIZED_NAME_ADMIN_CAPABILITY_CONFIG)
  private AdminCapabilityConfigDTO adminCapabilityConfig;

  public static final String SERIALIZED_NAME_ROLE_MODULES_CONFIG = "roleModulesConfig";
  @SerializedName(SERIALIZED_NAME_ROLE_MODULES_CONFIG)
  private RoleModulesConfigDTO roleModulesConfig;

  public PermissionDTO() {
  }

  public PermissionDTO description(String description) {
    
    
    
    
    this.description = description;
    return this;
  }

   /**
   * A user-defined description of the permission.
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A user-defined description of the permission.")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    
    
    
    this.description = description;
  }


  public PermissionDTO permissionId(String permissionId) {
    
    
    
    
    this.permissionId = permissionId;
    return this;
  }

   /**
   * The unique identifier associated with the permission.
   * @return permissionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The unique identifier associated with the permission.")

  public String getPermissionId() {
    return permissionId;
  }


  public void setPermissionId(String permissionId) {
    
    
    
    this.permissionId = permissionId;
  }


  public PermissionDTO displayName(String displayName) {
    
    
    
    
    this.displayName = displayName;
    return this;
  }

   /**
   * An identifiable permission name to display in Visier, such as \&quot;Diversity Access\&quot;.
   * @return displayName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An identifiable permission name to display in Visier, such as \"Diversity Access\".")

  public String getDisplayName() {
    return displayName;
  }


  public void setDisplayName(String displayName) {
    
    
    
    this.displayName = displayName;
  }


  public PermissionDTO dataSecurityProfiles(List<DataSecurityProfileDTO> dataSecurityProfiles) {
    
    
    
    
    this.dataSecurityProfiles = dataSecurityProfiles;
    return this;
  }

  public PermissionDTO addDataSecurityProfilesItem(DataSecurityProfileDTO dataSecurityProfilesItem) {
    if (this.dataSecurityProfiles == null) {
      this.dataSecurityProfiles = new ArrayList<>();
    }
    this.dataSecurityProfiles.add(dataSecurityProfilesItem);
    return this;
  }

   /**
   * A list of objects representing the data security profile configurations associated with the permission.
   * @return dataSecurityProfiles
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of objects representing the data security profile configurations associated with the permission.")

  public List<DataSecurityProfileDTO> getDataSecurityProfiles() {
    return dataSecurityProfiles;
  }


  public void setDataSecurityProfiles(List<DataSecurityProfileDTO> dataSecurityProfiles) {
    
    
    
    this.dataSecurityProfiles = dataSecurityProfiles;
  }


  public PermissionDTO adminCapabilityConfig(AdminCapabilityConfigDTO adminCapabilityConfig) {
    
    
    
    
    this.adminCapabilityConfig = adminCapabilityConfig;
    return this;
  }

   /**
   * The capability configuration associated with the permission.
   * @return adminCapabilityConfig
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The capability configuration associated with the permission.")

  public AdminCapabilityConfigDTO getAdminCapabilityConfig() {
    return adminCapabilityConfig;
  }


  public void setAdminCapabilityConfig(AdminCapabilityConfigDTO adminCapabilityConfig) {
    
    
    
    this.adminCapabilityConfig = adminCapabilityConfig;
  }


  public PermissionDTO roleModulesConfig(RoleModulesConfigDTO roleModulesConfig) {
    
    
    
    
    this.roleModulesConfig = roleModulesConfig;
    return this;
  }

   /**
   * The role modules configuration associated with the permission.
   * @return roleModulesConfig
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The role modules configuration associated with the permission.")

  public RoleModulesConfigDTO getRoleModulesConfig() {
    return roleModulesConfig;
  }


  public void setRoleModulesConfig(RoleModulesConfigDTO roleModulesConfig) {
    
    
    
    this.roleModulesConfig = roleModulesConfig;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PermissionDTO instance itself
   */
  public PermissionDTO putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PermissionDTO permissionDTO = (PermissionDTO) o;
    return Objects.equals(this.description, permissionDTO.description) &&
        Objects.equals(this.permissionId, permissionDTO.permissionId) &&
        Objects.equals(this.displayName, permissionDTO.displayName) &&
        Objects.equals(this.dataSecurityProfiles, permissionDTO.dataSecurityProfiles) &&
        Objects.equals(this.adminCapabilityConfig, permissionDTO.adminCapabilityConfig) &&
        Objects.equals(this.roleModulesConfig, permissionDTO.roleModulesConfig)&&
        Objects.equals(this.additionalProperties, permissionDTO.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, permissionId, displayName, dataSecurityProfiles, adminCapabilityConfig, roleModulesConfig, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PermissionDTO {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    permissionId: ").append(toIndentedString(permissionId)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    dataSecurityProfiles: ").append(toIndentedString(dataSecurityProfiles)).append("\n");
    sb.append("    adminCapabilityConfig: ").append(toIndentedString(adminCapabilityConfig)).append("\n");
    sb.append("    roleModulesConfig: ").append(toIndentedString(roleModulesConfig)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("description");
    openapiFields.add("permissionId");
    openapiFields.add("displayName");
    openapiFields.add("dataSecurityProfiles");
    openapiFields.add("adminCapabilityConfig");
    openapiFields.add("roleModulesConfig");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PermissionDTO
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PermissionDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PermissionDTO is not found in the empty JSON string", PermissionDTO.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if ((jsonObj.get("permissionId") != null && !jsonObj.get("permissionId").isJsonNull()) && !jsonObj.get("permissionId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `permissionId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("permissionId").toString()));
      }
      if ((jsonObj.get("displayName") != null && !jsonObj.get("displayName").isJsonNull()) && !jsonObj.get("displayName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `displayName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("displayName").toString()));
      }
      if (jsonObj.get("dataSecurityProfiles") != null && !jsonObj.get("dataSecurityProfiles").isJsonNull()) {
        JsonArray jsonArraydataSecurityProfiles = jsonObj.getAsJsonArray("dataSecurityProfiles");
        if (jsonArraydataSecurityProfiles != null) {
          // ensure the json data is an array
          if (!jsonObj.get("dataSecurityProfiles").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `dataSecurityProfiles` to be an array in the JSON string but got `%s`", jsonObj.get("dataSecurityProfiles").toString()));
          }

          // validate the optional field `dataSecurityProfiles` (array)
          for (int i = 0; i < jsonArraydataSecurityProfiles.size(); i++) {
            DataSecurityProfileDTO.validateJsonObject(jsonArraydataSecurityProfiles.get(i).getAsJsonObject());
          };
        }
      }
      // validate the optional field `adminCapabilityConfig`
      if (jsonObj.get("adminCapabilityConfig") != null && !jsonObj.get("adminCapabilityConfig").isJsonNull()) {
        AdminCapabilityConfigDTO.validateJsonObject(jsonObj.getAsJsonObject("adminCapabilityConfig"));
      }
      // validate the optional field `roleModulesConfig`
      if (jsonObj.get("roleModulesConfig") != null && !jsonObj.get("roleModulesConfig").isJsonNull()) {
        RoleModulesConfigDTO.validateJsonObject(jsonObj.getAsJsonObject("roleModulesConfig"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PermissionDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PermissionDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PermissionDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PermissionDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<PermissionDTO>() {
           @Override
           public void write(JsonWriter out, PermissionDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PermissionDTO read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PermissionDTO instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PermissionDTO given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PermissionDTO
  * @throws IOException if the JSON string is invalid with respect to PermissionDTO
  */
  public static PermissionDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PermissionDTO.class);
  }

 /**
  * Convert an instance of PermissionDTO to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

