/*
 * Visier Permission Management APIs
 * Visier APIs for managing permissions within an organization
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * PropertyAccessConfigDTO
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PropertyAccessConfigDTO {
  public static final String SERIALIZED_NAME_PROPERTY_ID = "propertyId";
  @SerializedName(SERIALIZED_NAME_PROPERTY_ID)
  private String propertyId;

  public static final String SERIALIZED_NAME_ANALYTIC_OBJECT_ID = "analyticObjectId";
  @SerializedName(SERIALIZED_NAME_ANALYTIC_OBJECT_ID)
  private String analyticObjectId;

  public static final String SERIALIZED_NAME_ANALYTIC_OBJECT_REFERENCE_PATHS = "analyticObjectReferencePaths";
  @SerializedName(SERIALIZED_NAME_ANALYTIC_OBJECT_REFERENCE_PATHS)
  private List<String> analyticObjectReferencePaths = null;

  /**
   * The access level of the property. Valid values are: Aggregate, Sensitive
   */
  @JsonAdapter(AccessLevelEnum.Adapter.class)
 public enum AccessLevelEnum {
    NONE("None"),
    
    AGGREGATE("Aggregate"),
    
    DETAILED("Detailed");

    private String value;

    AccessLevelEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static AccessLevelEnum fromValue(String value) {
      for (AccessLevelEnum b : AccessLevelEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<AccessLevelEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AccessLevelEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AccessLevelEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return AccessLevelEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_ACCESS_LEVEL = "accessLevel";
  @SerializedName(SERIALIZED_NAME_ACCESS_LEVEL)
  private AccessLevelEnum accessLevel;

  public PropertyAccessConfigDTO() {
  }

  public PropertyAccessConfigDTO propertyId(String propertyId) {
    
    
    
    
    this.propertyId = propertyId;
    return this;
  }

   /**
   * The property ID associated with the property access configuration.
   * @return propertyId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The property ID associated with the property access configuration.")

  public String getPropertyId() {
    return propertyId;
  }


  public void setPropertyId(String propertyId) {
    
    
    
    this.propertyId = propertyId;
  }


  public PropertyAccessConfigDTO analyticObjectId(String analyticObjectId) {
    
    
    
    
    this.analyticObjectId = analyticObjectId;
    return this;
  }

   /**
   * The analytic object ID of the property.
   * @return analyticObjectId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The analytic object ID of the property.")

  public String getAnalyticObjectId() {
    return analyticObjectId;
  }


  public void setAnalyticObjectId(String analyticObjectId) {
    
    
    
    this.analyticObjectId = analyticObjectId;
  }


  public PropertyAccessConfigDTO analyticObjectReferencePaths(List<String> analyticObjectReferencePaths) {
    
    
    
    
    this.analyticObjectReferencePaths = analyticObjectReferencePaths;
    return this;
  }

  public PropertyAccessConfigDTO addAnalyticObjectReferencePathsItem(String analyticObjectReferencePathsItem) {
    if (this.analyticObjectReferencePaths == null) {
      this.analyticObjectReferencePaths = new ArrayList<>();
    }
    this.analyticObjectReferencePaths.add(analyticObjectReferencePathsItem);
    return this;
  }

   /**
   * The path to the analytic object reference or empty if the configuration is not a reference.
   * @return analyticObjectReferencePaths
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The path to the analytic object reference or empty if the configuration is not a reference.")

  public List<String> getAnalyticObjectReferencePaths() {
    return analyticObjectReferencePaths;
  }


  public void setAnalyticObjectReferencePaths(List<String> analyticObjectReferencePaths) {
    
    
    
    this.analyticObjectReferencePaths = analyticObjectReferencePaths;
  }


  public PropertyAccessConfigDTO accessLevel(AccessLevelEnum accessLevel) {
    
    
    
    
    this.accessLevel = accessLevel;
    return this;
  }

   /**
   * The access level of the property. Valid values are: Aggregate, Sensitive
   * @return accessLevel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The access level of the property. Valid values are: Aggregate, Sensitive")

  public AccessLevelEnum getAccessLevel() {
    return accessLevel;
  }


  public void setAccessLevel(AccessLevelEnum accessLevel) {
    
    
    
    this.accessLevel = accessLevel;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PropertyAccessConfigDTO instance itself
   */
  public PropertyAccessConfigDTO putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PropertyAccessConfigDTO propertyAccessConfigDTO = (PropertyAccessConfigDTO) o;
    return Objects.equals(this.propertyId, propertyAccessConfigDTO.propertyId) &&
        Objects.equals(this.analyticObjectId, propertyAccessConfigDTO.analyticObjectId) &&
        Objects.equals(this.analyticObjectReferencePaths, propertyAccessConfigDTO.analyticObjectReferencePaths) &&
        Objects.equals(this.accessLevel, propertyAccessConfigDTO.accessLevel)&&
        Objects.equals(this.additionalProperties, propertyAccessConfigDTO.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(propertyId, analyticObjectId, analyticObjectReferencePaths, accessLevel, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PropertyAccessConfigDTO {\n");
    sb.append("    propertyId: ").append(toIndentedString(propertyId)).append("\n");
    sb.append("    analyticObjectId: ").append(toIndentedString(analyticObjectId)).append("\n");
    sb.append("    analyticObjectReferencePaths: ").append(toIndentedString(analyticObjectReferencePaths)).append("\n");
    sb.append("    accessLevel: ").append(toIndentedString(accessLevel)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("propertyId");
    openapiFields.add("analyticObjectId");
    openapiFields.add("analyticObjectReferencePaths");
    openapiFields.add("accessLevel");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PropertyAccessConfigDTO
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PropertyAccessConfigDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PropertyAccessConfigDTO is not found in the empty JSON string", PropertyAccessConfigDTO.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("propertyId") != null && !jsonObj.get("propertyId").isJsonNull()) && !jsonObj.get("propertyId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `propertyId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("propertyId").toString()));
      }
      if ((jsonObj.get("analyticObjectId") != null && !jsonObj.get("analyticObjectId").isJsonNull()) && !jsonObj.get("analyticObjectId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `analyticObjectId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("analyticObjectId").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("analyticObjectReferencePaths") != null && !jsonObj.get("analyticObjectReferencePaths").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `analyticObjectReferencePaths` to be an array in the JSON string but got `%s`", jsonObj.get("analyticObjectReferencePaths").toString()));
      }
      if ((jsonObj.get("accessLevel") != null && !jsonObj.get("accessLevel").isJsonNull()) && !jsonObj.get("accessLevel").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `accessLevel` to be a primitive type in the JSON string but got `%s`", jsonObj.get("accessLevel").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PropertyAccessConfigDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PropertyAccessConfigDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PropertyAccessConfigDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PropertyAccessConfigDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<PropertyAccessConfigDTO>() {
           @Override
           public void write(JsonWriter out, PropertyAccessConfigDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PropertyAccessConfigDTO read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PropertyAccessConfigDTO instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PropertyAccessConfigDTO given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PropertyAccessConfigDTO
  * @throws IOException if the JSON string is invalid with respect to PropertyAccessConfigDTO
  */
  public static PropertyAccessConfigDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PropertyAccessConfigDTO.class);
  }

 /**
  * Convert an instance of PropertyAccessConfigDTO to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

