/*
 * Visier Permission Management APIs
 * Visier APIs for managing permissions within an organization
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.HierarchyPropertyDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * SecurableDimensionDTO
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class SecurableDimensionDTO {
  public static final String SERIALIZED_NAME_DIMENSION_ID = "dimensionId";
  @SerializedName(SERIALIZED_NAME_DIMENSION_ID)
  private String dimensionId;

  public static final String SERIALIZED_NAME_DISPLAY_NAME = "displayName";
  @SerializedName(SERIALIZED_NAME_DISPLAY_NAME)
  private String displayName;

  public static final String SERIALIZED_NAME_ANALYTIC_OBJECT_IDS = "analyticObjectIds";
  @SerializedName(SERIALIZED_NAME_ANALYTIC_OBJECT_IDS)
  private List<String> analyticObjectIds = null;

  public static final String SERIALIZED_NAME_HIERARCHY_PROPERTIES = "hierarchyProperties";
  @SerializedName(SERIALIZED_NAME_HIERARCHY_PROPERTIES)
  private List<HierarchyPropertyDTO> hierarchyProperties = null;

  public SecurableDimensionDTO() {
  }

  public SecurableDimensionDTO dimensionId(String dimensionId) {
    
    
    
    
    this.dimensionId = dimensionId;
    return this;
  }

   /**
   * The dimension ID.
   * @return dimensionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The dimension ID.")

  public String getDimensionId() {
    return dimensionId;
  }


  public void setDimensionId(String dimensionId) {
    
    
    
    this.dimensionId = dimensionId;
  }


  public SecurableDimensionDTO displayName(String displayName) {
    
    
    
    
    this.displayName = displayName;
    return this;
  }

   /**
   * An identifiable dimension name to display in Visier, such as \&quot;Contract Type\&quot;.
   * @return displayName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An identifiable dimension name to display in Visier, such as \"Contract Type\".")

  public String getDisplayName() {
    return displayName;
  }


  public void setDisplayName(String displayName) {
    
    
    
    this.displayName = displayName;
  }


  public SecurableDimensionDTO analyticObjectIds(List<String> analyticObjectIds) {
    
    
    
    
    this.analyticObjectIds = analyticObjectIds;
    return this;
  }

  public SecurableDimensionDTO addAnalyticObjectIdsItem(String analyticObjectIdsItem) {
    if (this.analyticObjectIds == null) {
      this.analyticObjectIds = new ArrayList<>();
    }
    this.analyticObjectIds.add(analyticObjectIdsItem);
    return this;
  }

   /**
   * A list of analytic object IDs.
   * @return analyticObjectIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of analytic object IDs.")

  public List<String> getAnalyticObjectIds() {
    return analyticObjectIds;
  }


  public void setAnalyticObjectIds(List<String> analyticObjectIds) {
    
    
    
    this.analyticObjectIds = analyticObjectIds;
  }


  public SecurableDimensionDTO hierarchyProperties(List<HierarchyPropertyDTO> hierarchyProperties) {
    
    
    
    
    this.hierarchyProperties = hierarchyProperties;
    return this;
  }

  public SecurableDimensionDTO addHierarchyPropertiesItem(HierarchyPropertyDTO hierarchyPropertiesItem) {
    if (this.hierarchyProperties == null) {
      this.hierarchyProperties = new ArrayList<>();
    }
    this.hierarchyProperties.add(hierarchyPropertiesItem);
    return this;
  }

   /**
   * The list of hierarchies you can map to a user in a permission&#39;s dynamic filter.
   * @return hierarchyProperties
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The list of hierarchies you can map to a user in a permission's dynamic filter.")

  public List<HierarchyPropertyDTO> getHierarchyProperties() {
    return hierarchyProperties;
  }


  public void setHierarchyProperties(List<HierarchyPropertyDTO> hierarchyProperties) {
    
    
    
    this.hierarchyProperties = hierarchyProperties;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the SecurableDimensionDTO instance itself
   */
  public SecurableDimensionDTO putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SecurableDimensionDTO securableDimensionDTO = (SecurableDimensionDTO) o;
    return Objects.equals(this.dimensionId, securableDimensionDTO.dimensionId) &&
        Objects.equals(this.displayName, securableDimensionDTO.displayName) &&
        Objects.equals(this.analyticObjectIds, securableDimensionDTO.analyticObjectIds) &&
        Objects.equals(this.hierarchyProperties, securableDimensionDTO.hierarchyProperties)&&
        Objects.equals(this.additionalProperties, securableDimensionDTO.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dimensionId, displayName, analyticObjectIds, hierarchyProperties, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SecurableDimensionDTO {\n");
    sb.append("    dimensionId: ").append(toIndentedString(dimensionId)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    analyticObjectIds: ").append(toIndentedString(analyticObjectIds)).append("\n");
    sb.append("    hierarchyProperties: ").append(toIndentedString(hierarchyProperties)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("dimensionId");
    openapiFields.add("displayName");
    openapiFields.add("analyticObjectIds");
    openapiFields.add("hierarchyProperties");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to SecurableDimensionDTO
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!SecurableDimensionDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SecurableDimensionDTO is not found in the empty JSON string", SecurableDimensionDTO.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("dimensionId") != null && !jsonObj.get("dimensionId").isJsonNull()) && !jsonObj.get("dimensionId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dimensionId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dimensionId").toString()));
      }
      if ((jsonObj.get("displayName") != null && !jsonObj.get("displayName").isJsonNull()) && !jsonObj.get("displayName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `displayName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("displayName").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("analyticObjectIds") != null && !jsonObj.get("analyticObjectIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `analyticObjectIds` to be an array in the JSON string but got `%s`", jsonObj.get("analyticObjectIds").toString()));
      }
      if (jsonObj.get("hierarchyProperties") != null && !jsonObj.get("hierarchyProperties").isJsonNull()) {
        JsonArray jsonArrayhierarchyProperties = jsonObj.getAsJsonArray("hierarchyProperties");
        if (jsonArrayhierarchyProperties != null) {
          // ensure the json data is an array
          if (!jsonObj.get("hierarchyProperties").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `hierarchyProperties` to be an array in the JSON string but got `%s`", jsonObj.get("hierarchyProperties").toString()));
          }

          // validate the optional field `hierarchyProperties` (array)
          for (int i = 0; i < jsonArrayhierarchyProperties.size(); i++) {
            HierarchyPropertyDTO.validateJsonObject(jsonArrayhierarchyProperties.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SecurableDimensionDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SecurableDimensionDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SecurableDimensionDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SecurableDimensionDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<SecurableDimensionDTO>() {
           @Override
           public void write(JsonWriter out, SecurableDimensionDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public SecurableDimensionDTO read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             SecurableDimensionDTO instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SecurableDimensionDTO given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SecurableDimensionDTO
  * @throws IOException if the JSON string is invalid with respect to SecurableDimensionDTO
  */
  public static SecurableDimensionDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SecurableDimensionDTO.class);
  }

 /**
  * Convert an instance of SecurableDimensionDTO to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

