/*
 * Visier Permission Management APIs
 * Visier APIs for managing permissions within an organization
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * SecurablePropertyDTO
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class SecurablePropertyDTO {
  public static final String SERIALIZED_NAME_PROPERTY_ID = "propertyId";
  @SerializedName(SERIALIZED_NAME_PROPERTY_ID)
  private String propertyId;

  public static final String SERIALIZED_NAME_DISPLAY_NAME = "displayName";
  @SerializedName(SERIALIZED_NAME_DISPLAY_NAME)
  private String displayName;

  public static final String SERIALIZED_NAME_ANALYTIC_OBJECT_ID = "analyticObjectId";
  @SerializedName(SERIALIZED_NAME_ANALYTIC_OBJECT_ID)
  private String analyticObjectId;

  public static final String SERIALIZED_NAME_IS_PRIMARY_KEY = "isPrimaryKey";
  @SerializedName(SERIALIZED_NAME_IS_PRIMARY_KEY)
  private Boolean isPrimaryKey;

  public static final String SERIALIZED_NAME_REFERENCE_SYMBOL_NAME = "referenceSymbolName";
  @SerializedName(SERIALIZED_NAME_REFERENCE_SYMBOL_NAME)
  private String referenceSymbolName;

  public SecurablePropertyDTO() {
  }

  public SecurablePropertyDTO propertyId(String propertyId) {
    
    
    
    
    this.propertyId = propertyId;
    return this;
  }

   /**
   * The property ID.
   * @return propertyId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The property ID.")

  public String getPropertyId() {
    return propertyId;
  }


  public void setPropertyId(String propertyId) {
    
    
    
    this.propertyId = propertyId;
  }


  public SecurablePropertyDTO displayName(String displayName) {
    
    
    
    
    this.displayName = displayName;
    return this;
  }

   /**
   * An identifiable property name to display in Visier, such as \&quot;Job Pay Level\&quot;.
   * @return displayName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An identifiable property name to display in Visier, such as \"Job Pay Level\".")

  public String getDisplayName() {
    return displayName;
  }


  public void setDisplayName(String displayName) {
    
    
    
    this.displayName = displayName;
  }


  public SecurablePropertyDTO analyticObjectId(String analyticObjectId) {
    
    
    
    
    this.analyticObjectId = analyticObjectId;
    return this;
  }

   /**
   * The property&#39;s analytic object ID.
   * @return analyticObjectId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The property's analytic object ID.")

  public String getAnalyticObjectId() {
    return analyticObjectId;
  }


  public void setAnalyticObjectId(String analyticObjectId) {
    
    
    
    this.analyticObjectId = analyticObjectId;
  }


  public SecurablePropertyDTO isPrimaryKey(Boolean isPrimaryKey) {
    
    
    
    
    this.isPrimaryKey = isPrimaryKey;
    return this;
  }

   /**
   * If true, this property is the analytic object&#39;s primary key.
   * @return isPrimaryKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If true, this property is the analytic object's primary key.")

  public Boolean getIsPrimaryKey() {
    return isPrimaryKey;
  }


  public void setIsPrimaryKey(Boolean isPrimaryKey) {
    
    
    
    this.isPrimaryKey = isPrimaryKey;
  }


  public SecurablePropertyDTO referenceSymbolName(String referenceSymbolName) {
    
    
    
    
    this.referenceSymbolName = referenceSymbolName;
    return this;
  }

   /**
   * The reference symbol name.
   * @return referenceSymbolName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The reference symbol name.")

  public String getReferenceSymbolName() {
    return referenceSymbolName;
  }


  public void setReferenceSymbolName(String referenceSymbolName) {
    
    
    
    this.referenceSymbolName = referenceSymbolName;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the SecurablePropertyDTO instance itself
   */
  public SecurablePropertyDTO putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SecurablePropertyDTO securablePropertyDTO = (SecurablePropertyDTO) o;
    return Objects.equals(this.propertyId, securablePropertyDTO.propertyId) &&
        Objects.equals(this.displayName, securablePropertyDTO.displayName) &&
        Objects.equals(this.analyticObjectId, securablePropertyDTO.analyticObjectId) &&
        Objects.equals(this.isPrimaryKey, securablePropertyDTO.isPrimaryKey) &&
        Objects.equals(this.referenceSymbolName, securablePropertyDTO.referenceSymbolName)&&
        Objects.equals(this.additionalProperties, securablePropertyDTO.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(propertyId, displayName, analyticObjectId, isPrimaryKey, referenceSymbolName, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SecurablePropertyDTO {\n");
    sb.append("    propertyId: ").append(toIndentedString(propertyId)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    analyticObjectId: ").append(toIndentedString(analyticObjectId)).append("\n");
    sb.append("    isPrimaryKey: ").append(toIndentedString(isPrimaryKey)).append("\n");
    sb.append("    referenceSymbolName: ").append(toIndentedString(referenceSymbolName)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("propertyId");
    openapiFields.add("displayName");
    openapiFields.add("analyticObjectId");
    openapiFields.add("isPrimaryKey");
    openapiFields.add("referenceSymbolName");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to SecurablePropertyDTO
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!SecurablePropertyDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SecurablePropertyDTO is not found in the empty JSON string", SecurablePropertyDTO.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("propertyId") != null && !jsonObj.get("propertyId").isJsonNull()) && !jsonObj.get("propertyId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `propertyId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("propertyId").toString()));
      }
      if ((jsonObj.get("displayName") != null && !jsonObj.get("displayName").isJsonNull()) && !jsonObj.get("displayName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `displayName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("displayName").toString()));
      }
      if ((jsonObj.get("analyticObjectId") != null && !jsonObj.get("analyticObjectId").isJsonNull()) && !jsonObj.get("analyticObjectId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `analyticObjectId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("analyticObjectId").toString()));
      }
      if ((jsonObj.get("referenceSymbolName") != null && !jsonObj.get("referenceSymbolName").isJsonNull()) && !jsonObj.get("referenceSymbolName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `referenceSymbolName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("referenceSymbolName").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SecurablePropertyDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SecurablePropertyDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SecurablePropertyDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SecurablePropertyDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<SecurablePropertyDTO>() {
           @Override
           public void write(JsonWriter out, SecurablePropertyDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public SecurablePropertyDTO read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             SecurablePropertyDTO instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SecurablePropertyDTO given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SecurablePropertyDTO
  * @throws IOException if the JSON string is invalid with respect to SecurablePropertyDTO
  */
  public static SecurablePropertyDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SecurablePropertyDTO.class);
  }

 /**
  * Convert an instance of SecurablePropertyDTO to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

