/*
 * Visier Permission Management APIs
 * Visier APIs for managing permissions within an organization
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.CapabilityDTO;
import com.konfigthis.client.model.ContentPackageDTO;
import com.konfigthis.client.model.GetCapabilitiesAPIResponseDTO;
import com.konfigthis.client.model.GetContentPackagesAPIResponseDTO;
import com.konfigthis.client.model.GetDataSecurityObjectsAPIResponseDTO;
import com.konfigthis.client.model.GetPermissionsAPIResponseDTO;
import com.konfigthis.client.model.PermissionBulkOperationResponseDTO;
import com.konfigthis.client.model.PermissionDTO;
import com.konfigthis.client.model.PermissionsListDTO;
import com.konfigthis.client.model.Status;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PermissionManagementApi
 */
@Disabled
public class PermissionManagementApiTest {

    private static PermissionManagementApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new PermissionManagementApi(apiClient);
    }

    /**
     * Create permissions
     *
     * This API allows you to create new permissions. Administrating tenant users can specify the tenant in which to add these permissions.   &lt;br&gt;**Note:** &lt;em&gt;This API is in **limited availability**. If you are interested in using it, please contact your Customer Success Manager (CSM).&lt;/em&gt;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createPermissionsTest() throws ApiException {
        List<PermissionDTO> permissions = null;
        String tenantCode = null;
        PermissionBulkOperationResponseDTO response = api.createPermissions()
                .permissions(permissions)
                .tenantCode(tenantCode)
                .execute();
        // TODO: test validations
    }

    /**
     * Delete permissions
     *
     * This API allows you to delete existing permissions.   &lt;br&gt;**Note:** &lt;em&gt;This API is in **limited availability**. If you are interested in using it, please contact your Customer Success Manager (CSM).&lt;/em&gt;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deletePermissionsTest() throws ApiException {
        String tenantCode = null;
        PermissionBulkOperationResponseDTO response = api.deletePermissions()
                .tenantCode(tenantCode)
                .execute();
        // TODO: test validations
    }

    /**
     * Retrieve a list of all permission capabilities
     *
     * This API allows you to retrieve all the permission capabilities in your tenant.  You can use the returned capabilities in other API calls when creating or updating permissions to assign the capability to the permission.   &lt;br&gt;**Note:** &lt;em&gt;This API is in **limited availability**. If you are interested in using it, please contact your Customer Success Manager (CSM).&lt;/em&gt;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCapabilitiesTest() throws ApiException {
        String tenantCode = null;
        GetCapabilitiesAPIResponseDTO response = api.getCapabilities()
                .tenantCode(tenantCode)
                .execute();
        // TODO: test validations
    }

    /**
     * Retrieve a permission capability&#39;s details
     *
     * This API allows you to retrieve the details of a specific capability.   &lt;br&gt;**Note:** &lt;em&gt;This API is in **limited availability**. If you are interested in using it, please contact your Customer Success Manager (CSM).&lt;/em&gt;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCapabilityTest() throws ApiException {
        String capabilityId = null;
        String tenantCode = null;
        CapabilityDTO response = api.getCapability(capabilityId)
                .tenantCode(tenantCode)
                .execute();
        // TODO: test validations
    }

    /**
     * Retrieve a content package&#39;s details
     *
     * This API allows you to retrieve the details of a specific content package.   &lt;br&gt;**Note:** &lt;em&gt;This API is in **limited availability**. If you are interested in using it, please contact your Customer Success Manager (CSM).&lt;/em&gt;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getContentPackageTest() throws ApiException {
        String contentPackageId = null;
        String tenantCode = null;
        ContentPackageDTO response = api.getContentPackage(contentPackageId)
                .tenantCode(tenantCode)
                .execute();
        // TODO: test validations
    }

    /**
     * Retrieve a list of all content packages
     *
     * This API allows you to retrieve the list of available content packages.  You can use the returned content packages in other API calls when creating or updating permissions to add the content package to the permission.   &lt;br&gt;**Note:** &lt;em&gt;This API is in **limited availability**. If you are interested in using it, please contact your Customer Success Manager (CSM).&lt;/em&gt;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getContentPackagesTest() throws ApiException {
        String tenantCode = null;
        String searchString = null;
        GetContentPackagesAPIResponseDTO response = api.getContentPackages()
                .tenantCode(tenantCode)
                .searchString(searchString)
                .execute();
        // TODO: test validations
    }

    /**
     * Retrieve a list of data security objects
     *
     * This API allows you to retrieve the list of available data security objects.  Data security objects are analytic objects and their related objects that are available to define  permissions’ data security profiles.   &lt;br&gt;**Note:** &lt;em&gt;This API is in **limited availability**. If you are interested in using it, please contact your Customer Success Manager (CSM).&lt;/em&gt;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDataSecurityObjectsTest() throws ApiException {
        List<String> id = null;
        Boolean includeDetails = null;
        String tenantCode = null;
        GetDataSecurityObjectsAPIResponseDTO response = api.getDataSecurityObjects()
                .id(id)
                .includeDetails(includeDetails)
                .tenantCode(tenantCode)
                .execute();
        // TODO: test validations
    }

    /**
     * Retrieve a permission&#39;s details
     *
     * This API allows you to retrieve the details for a specified permission.   &lt;br&gt;**Note:** &lt;em&gt;This API is in **limited availability**. If you are interested in using it, please contact your Customer Success Manager (CSM).&lt;/em&gt;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPermissionTest() throws ApiException {
        String permissionId = null;
        String tenantCode = null;
        PermissionDTO response = api.getPermission(permissionId)
                .tenantCode(tenantCode)
                .execute();
        // TODO: test validations
    }

    /**
     * Retrieve a list of all permissions
     *
     * This API allows you to retrieve the full list of user permissions in your tenant.   &lt;br&gt;**Note:** &lt;em&gt;This API is in **limited availability**. If you are interested in using it, please contact your Customer Success Manager (CSM).&lt;/em&gt;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPermissionsTest() throws ApiException {
        String tenantCode = null;
        Boolean includeDetails = null;
        GetPermissionsAPIResponseDTO response = api.getPermissions()
                .tenantCode(tenantCode)
                .includeDetails(includeDetails)
                .execute();
        // TODO: test validations
    }

    /**
     * Update permissions
     *
     * This API allows you to update existing permissions.   &lt;br&gt;**Note:** &lt;em&gt;This API is in **limited availability**. If you are interested in using it, please contact your Customer Success Manager (CSM).&lt;/em&gt;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updatePermissionsTest() throws ApiException {
        List<PermissionDTO> permissions = null;
        String tenantCode = null;
        PermissionBulkOperationResponseDTO response = api.updatePermissions()
                .permissions(permissions)
                .tenantCode(tenantCode)
                .execute();
        // TODO: test validations
    }

}
